// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__talent_widget': string;
  'root__talent_wrapper': string;
  'root__talent_wrapper_place': string;
  'root__talent_wrapper_title': string;
}
export const cssExports: CssExports;
export default cssExports;
